// trabalho-livros-next/pages/LivroDados.tsx
import React, { useState } from 'react';
import Head from 'next/head';
import Router from 'next/router';
import styles from '../styles/Home.module.css';
import 'bootstrap/dist/css/bootstrap.css';
import { ControleEditora } from '../classes/controle/ControleEditora';
import { Livro } from '../classes/modelo/Livro';

const controleEditora = new ControleEditora();

const LivroDados = () => {
  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');
  const [codEditora, setCodEditora] = useState<number>(
    controleEditora.getEditoras()[0].codEditora
  );

  const incluirLivro = async (livro: Livro) => {
    const response = await fetch('/api/livros', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(livro),
    });
    return response.ok;
  };

  const incluir = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const livro: Livro = {
      codigo: "",
      titulo,
      resumo,
      autores: autores.split('\n'),
      codEditora,
      
    };
    incluirLivro(livro).then(() => Router.push('/LivroLista'));
  };

  return (
    <div className={styles.containers}>
      <Head>
        <title>Loja Next - Novo Livro</title>
      </Head>
      <main className={styles.mainDados}>
        <h1 className={styles.title}>Cadastrar Novo Livro</h1>
        <form onSubmit={incluir}>
          <div className="form-group">
            <label htmlFor="titulo">Título</label>
            <input
              type="text"
              className="form-control mt-2"
              id="titulo"
              value={titulo}
              onChange={(e) => setTitulo(e.target.value)}
              required
            />
          </div>
          <div className="form-group">
            <label htmlFor="resumo">Resumo</label>
            <textarea
              className="form-control mt-2"
              id="resumo"
              value={resumo}
              onChange={(e) => setResumo(e.target.value)}
              required
            />
          </div>
          <div className="form-group">
            <label htmlFor="autores">Autores (um por linha)</label>
            <textarea
              className="form-control mt-2"
              id="autores"
              value={autores}
              onChange={(e) => setAutores(e.target.value)}
              required
            />
          </div>
          <div className="form-group">
            <label htmlFor="editora">Editora</label>
            <select
              className="form-control mt-2"
              id="editora"
              value={codEditora}
              onChange={(e) => setCodEditora(Number(e.target.value))}>
              {controleEditora.getEditoras().map((editora) => (
                <option key={editora.codEditora} value={editora.codEditora}>
                  {editora.nome}
                </option>
              ))}
            </select>
          </div>
          <button type="submit" className="btn btn-primary mt-3">
            Salvar
          </button>
        </form>
      </main>
    </div>
  );
};

export default LivroDados;

// livros-angular/src/app/livro-dados/livro-dados.component.ts
// livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro, LivroSemId } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-livro-dados',
  standalone: true,
  imports:[CommonModule, FormsModule],
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro('',0, '', '',[]);
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    public router: Router
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = async () => {
    // Cria o livro sem _id
    const livroParaIncluir: LivroSemId = {
      codEditora: this.livro.codEditora,
      titulo: this.livro.titulo,
      resumo: this.livro.resumo,
      autores: this.autoresForm.split('\n').map(autor => autor.trim())
    };

    // Chama o serviço para incluir o livro
    const sucesso = await this.servLivros.incluirLivro(livroParaIncluir);

    if (sucesso) {
      this.router.navigateByUrl('/lista');
    } else {
      alert('Erro ao incluir o livro. Tente novamente.');
    }
  };
}

<main class="container mt-4">
  <h1>Dados do Livro</h1>
  <form (submit)="incluir()" ngNativeValidate>
    <div class="mb-3">
      <label for="titulo" class="form-label">Título</label>
      <input type="text" id="titulo" class="form-control" [(ngModel)]="livro.titulo" name="titulo" required>
    </div>
    <div class="mb-3">
      <label for="resumo" class="form-label">Resumo</label>
      <textarea id="resumo" class="form-control" [(ngModel)]="livro.resumo" name="resumo"></textarea>
    </div>
    <div class="mb-3">
      <label for="editora" class="form-label mr-3">Editora</label>
      <select id="editora" class="form-select" [(ngModel)]="livro.codEditora" name="editora" required>
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
      </select>
    </div>
    <div class="mb-3">
      <label for="autores" class="form-label">Autores (1 por linha)</label>
      <textarea id="autores" class="form-control" [(ngModel)]="autoresForm" name="autores"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Salvar Dados</button>
  </form>
</main>
