// trabalho-livros-react/src/LivroDados.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ControleLivros } from './controle/ControleLivros';
import { ControleEditora } from './controle/ControleEditora';

const controleLivro = new ControleLivros(); // Crie uma instância da classe ControleLivros
const controleEditora = new ControleEditora();

const LivroDados = () => {
    const navigate = useNavigate();
    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [autores, setAutores] = useState('');
    const [codEditora, setCodEditora] = useState(0);
    const opcoes = controleEditora.getEditoras().map(editora => ({
        value: editora.codEditora,
        text: editora.nome
    }));

    const tratarCombo = (event) => {
        setCodEditora(Number(event.target.value));
    };

    const incluir = async (event) => {
        event.preventDefault();
        const livro = {
            codigo: 0,
            codEditora,
            titulo,
            resumo,
            autores: autores.split('\n')
        };
        await controleLivro.incluirLivro(livro); // Chame o método na instância
        navigate('/');
    };

    return (
        <main className="container mt-4">
            <h1>Cadastro de Livro</h1>
            <form onSubmit={incluir}>
                <div className="form-group">
                    <label htmlFor="titulo">Título:</label>
                    <input
                        type="text"
                        id="titulo"
                        className="form-control"
                        value={titulo}
                        onChange={(e) => setTitulo(e.target.value)}
                    />
                </div>
                <div className="form-group">
                    <label htmlFor="resumo">Resumo:</label>
                    <textarea
                        id="resumo"
                        className="form-control"
                        value={resumo}
                        onChange={(e) => setResumo(e.target.value)}
                    />
                </div>
                <div className="form-group">
                    <label htmlFor="autores">Autores (separados por linha):</label>
                    <textarea
                        id="autores"
                        className="form-control"
                        value={autores}
                        onChange={(e) => setAutores(e.target.value)}
                    />
                </div>
                <div className="form-group">
                    <label htmlFor="codEditora">Editora:</label>
                    <select
                        id="codEditora"
                        className="form-control"
                        value={codEditora}
                        onChange={tratarCombo}
                    >
                        {opcoes.map(opcao => (
                            <option key={opcao.value} value={opcao.value}>{opcao.text}</option>
                        ))}
                    </select>
                </div>
                <button type="submit" className="btn btn-primary">Salvar</button>
            </form>
        </main>
    );
};

export default LivroDados;

// livros-angular/src/app/livro-dados/livro-dados.component.ts
// livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro, LivroSemId } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-livro-dados',
  standalone: true,
  imports:[CommonModule, FormsModule],
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro('',0, '', '',[]);
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    public router: Router
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = async () => {
    // Cria o livro sem _id
    const livroParaIncluir: LivroSemId = {
      codEditora: this.livro.codEditora,
      titulo: this.livro.titulo,
      resumo: this.livro.resumo,
      autores: this.autoresForm.split('\n').map(autor => autor.trim())
    };

    // Chama o serviço para incluir o livro
    const sucesso = await this.servLivros.incluirLivro(livroParaIncluir);

    if (sucesso) {
      this.router.navigateByUrl('/lista');
    } else {
      alert('Erro ao incluir o livro. Tente novamente.');
    }
  };
}

<main class="container mt-4">
  <h1>Dados do Livro</h1>
  <form (submit)="incluir()" ngNativeValidate>
    <div class="mb-3">
      <label for="titulo" class="form-label">Título</label>
      <input type="text" id="titulo" class="form-control" [(ngModel)]="livro.titulo" name="titulo" required>
    </div>
    <div class="mb-3">
      <label for="resumo" class="form-label">Resumo</label>
      <textarea id="resumo" class="form-control" [(ngModel)]="livro.resumo" name="resumo"></textarea>
    </div>
    <div class="mb-3">
      <label for="editora" class="form-label mr-3">Editora</label>
      <select id="editora" class="form-select" [(ngModel)]="livro.codEditora" name="editora" required>
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
      </select>
    </div>
    <div class="mb-3">
      <label for="autores" class="form-label">Autores (1 por linha)</label>
      <textarea id="autores" class="form-control" [(ngModel)]="autoresForm" name="autores"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Salvar Dados</button>
  </form>
</main>
